vendor: update with govendor fetch +missing
Previously `govendor sync` would result in a failed build due to hitting
this issue: https://github.com/fatih/color/issues/62.

```
==> govendor sync
==> go build -o /usr/local/Cellar/wsk/0.9.0-incubating/bin/wsk
\# github.com/apache/incubator-openwhisk-cli/vendor/github.com/fatih/color
vendor/github.com/fatih/color/color.go:21:43: undefined: isatty.IsCygwinTerminal
```

My knowledge of `govendor` isn't wildly comprehensive but as far as I'm
aware `govendor fetch +missing` is a pretty standard way of
initialising things upstream so packagers/users only ever need to run
`govendor sync`.

Ref: https://github.com/apache/incubator-openwhisk-cli/pull/362